import vazirfont from '@/constants/localFonts'
import '../../globals.css'
import { Toaster } from 'react-hot-toast'
import Providers from '../../providers'
import SideBar from './SideBar'
import FooterPage from '@/pages/Footer'

export const metadata = {
  title: 'پروفایل کاربر',
  
  description: 'Generated by mohamadYagma',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirfont.variable} font-sans` }>
        <Providers>
          <Toaster />
          <div className='grid grid-cols-5 bg-whie h-screen'>
            <div className='col-span-1 bg-gray-100 overflow-y-auto p-4'>
                <SideBar />
            </div>
            <div className='col-span-4 overflow-y-auto p-4 xl:max-w-screen-xl'>
              {children}   
            </div>
          </div>
          <FooterPage/>
        </Providers> 
      </body>
    </html>
  )
}
