import vazirfont from '@/constants/localFonts'
import './globals.css'
import Header from './Header'
import { Toaster } from 'react-hot-toast'
import Providers from './providers'

export const metadata = {
  title: 'AdminPanel',
  description: 'Generated by mohamadYagma',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${vazirfont.variable} font-sans` }>
        <Providers>
          <Toaster />
          <Header/>
          <div className='container xl:max-w-screen-xl'>
            {children}   
          </div>
        </Providers> 
      </body>
    </html>
  )
}
