import vazirfont from '@/constants/localFonts'
import './globals.css'

export const metadata = {
  title: 'AdminPanel',
  description: 'Generated by mohamadYagma',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${vazirfont.variable} font-sans`}>{children}</body>
    </html>
  )
}
