import vazirfont from '@/constants/localFonts'
import '../globals.css'
import Header from '../Header'
import { Toaster } from 'react-hot-toast'
import Providers from '../providers'
import FooterPage from '../Footer'





export const metadata = {
  title: 'AdminPanel',
  description: 'Generated by mohamadYagma',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirfont.variable} font-sans flex flex-col min-h-screen` }>
        <Providers>
          <Toaster />
          <Header />
          <div className='container xl:max-w-screen-xl flex-grow'>
            {children}   
          </div>
          <FooterPage/>
        </Providers> 
      </body>
    </html>
  )
}
